const path = require('node:path');
const {pathToFileURL} = require('node:url');

// Reuse the CLI's own handlers, presentation, validation and exit classification.
// Only canonical operations generated by the Settings helper are accepted.
function context(args, deviceId, operatorPackage, logger) {
  if (!['open', 'click', 'scroll', 'snapshot', 'screenshot', 'read-value'].includes(args[0])) {
    throw Error('Unsupported experimental API operation');
  }
  if (!deviceId?.trim() || !operatorPackage?.trim()) throw Error('Explicit device and Operator required');
  return {argv: args, rest: args.slice(1), format: 'json', explicitJsonOutput: true,
    verbose: false, noDaemon: true, deviceId, operatorPackage, logger};
}

let modules;
async function execute(args, options) {
  const load = relative => import(pathToFileURL(path.resolve(__dirname, '../../apps/node/dist', relative)).href);
  modules ??= Promise.all([load('cli/registry.js'), load('adapters/logger.js'), load('cli/stdoutExitCode.js')]);
  const [{COMMANDS}, {createAndroperatorLogger}, {shouldCliStdoutForceExitCode1}] = await modules;
  const logger = createAndroperatorLogger({logDir: options.logDir, outputFormat: 'json'});
  const ctx = context(args, process.env.ANDROPERATOR_DEVICE_ID, process.env.ANDROPERATOR_OPERATOR_PACKAGE, logger);
  const stdout = await COMMANDS[args[0]].handler(ctx);
  if (typeof stdout !== 'string') throw Error('Command handler returned no structured response');
  return {stdout, status: shouldCliStdoutForceExitCode1(stdout, false) ? 1 : 0, signal: null};
}

module.exports = {context, execute};
