export const DEFAULT_EMULATOR_AVD_NAME = "androperator-pixel";
export const SUPPORTED_EMULATOR_API_LEVEL = 35;
export const DEFAULT_EMULATOR_DEVICE_PROFILE = "pixel_7";
export const DEFAULT_EMULATOR_DATA_PARTITION_SIZE = "12G";
export const SUPPORTED_EMULATOR_ABIS = ["arm64-v8a"] as const;
export const DEFAULT_EMULATOR_ABI = SUPPORTED_EMULATOR_ABIS[0];
export const SUPPORTED_EMULATOR_DEVICE_PROFILES = [DEFAULT_EMULATOR_DEVICE_PROFILE] as const;
export const DEFAULT_EMULATOR_TAG = "google_apis_playstore";

export const DEFAULT_EMULATOR_SYSTEM_IMAGE = [
  "system-images",
  `android-${SUPPORTED_EMULATOR_API_LEVEL}`,
  DEFAULT_EMULATOR_TAG,
  DEFAULT_EMULATOR_ABI,
].join(";");


export { EMULATOR_DATA_PARTITION_SIZE_PATTERN, EMULATOR_BOOT_TIMEOUT_MS, ADB_REGISTRATION_TIMEOUT_MS, BOOT_POLL_INTERVAL_MS } from "../../adapters/android-emulator/constants.js";
